### ISSUE TITLE
where to write my path of images ?

### ISSUE THREAD

**Issue by Ng-ms** [devnag/pytorch-generative-adversarial-networks#11]
i want to run this code on my dataset , how can i do it ?

**Comment by hajarhomayouni** [comment]
I have the same question. I cannot find the line of code where the dataset is imported.

**Comment by benjavides** [comment]
He doesn't use a dataset but a distribution. He get's the values from it using `d_sampler` on line 142 in `gan_pytorch.py`

**Comment by devnag** [comment]
That's right, you'll need to adapt get_distribution_sampler() with your own dataset, rather than the random sampling from the target Gaussian.
