### ISSUE TITLE
Does this line train the discriminator?

### ISSUE THREAD

**Issue by wjmolina** [devnag/pytorch-generative-adversarial-networks#14]
https://github.com/devnag/pytorch-generative-adversarial-networks/blob/dc8685caf88bb028fa077cf59bed4ff2360f755a/gan_pytorch.py#L167

Nothing is being detached, so does this train the discriminator?

**Comment by TianshangLiu** [comment]
just train generator. you can compare D's parameters before and after  g_optimizer.step() , you'll find D's parameters not change.

**Comment by wjmolina** [comment]
Thanks!
