### ISSUE TITLE
what does decorate_with_diffs do?

### ISSUE THREAD

**Issue by rajarsheem** [devnag/pytorch-generative-adversarial-networks#2]
Can you please explain what does decorate_with_diffs() does ? Thanks.

**Comment by devnag** [comment]
It takes the existing raw distribution and also adds the squared distance of each point from the mean as extra information for the discriminator.

**Comment by rajarsheem** [comment]
"Squared distance of each point from the mean" -- Are you talking about something like variance ?

**Comment by devnag** [comment]
Yes, the variance is the mean, or expectation, of this distribution of diffs.
