### ISSUE TITLE
early stop？

### ISSUE THREAD

**Issue by xueliang** [devnag/pytorch-generative-adversarial-networks#3]
The best results is on about 18400 epochs. After that the mean value of faked data increases quickly. Is that any early stop strategy when training GAN?

**Comment by devnag** [comment]
Yes, there are some cases when you would want to try an early stopping strategy (in many optimization problems). Your best result may have been on 18.4k epochs in one run but if you run it several times you'll see that the peak is at different times, meaning it's sensitive to the initial random seeds (and the hyperparameters, of course).
