### ISSUE TITLE
Why the input dimension of D is 100?

### ISSUE THREAD

**Issue by cloudygoose** [devnag/pytorch-generative-adversarial-networks#4]
in the code we have "d_input_size = 100", which is very strange, the input dimension of the discriminator should be same as the output dimension of the generator, which is 1

**Comment by devnag** [comment]
Take a look at these comments on the blog post:
https://medium.com/@JordanEvanCampbell/hi-thanks-for-the-great-intro-2cbafeb27e6a
https://medium.com/@devnag/its-actually-not-quite-vanilla-gan-because-of-the-batching-d-input-size-100-that-allows-d-to-4f0a2199b17b

**Comment by cloudygoose** [comment]
I see, thanks~
