### ISSUE TITLE
torch.mean() gives error in line 80

### ISSUE THREAD

**Issue by Spandan-Madan** [devnag/pytorch-generative-adversarial-networks#6]
I think this is probably because of the updates, but torch.mean() no longer accepts the keep_dim = True argument.

I removed it and the code runs fine. Probably you need to remove it in the code!

**Comment by devnag** [comment]
This was actually a fix for pytorch 0.2.0 that we added a few weeks ago. Are you using python 3.6, pytorch 0.2.0? I just tested on python 3.6.0 + pytorch 0.2.0-py36_4cu75 right now and it works fine, though with a warning.

**Comment by Spandan-Madan** [comment]
Thanks! Closing the issue!
